include $(wildcard $(ARCHDIR)/include/Device/CPU/*/Makefile)
KERNEL_ARCH_OBJS+=$(patsubst %.c,%.o,$(wildcard $(ARCHDIR)/include/Device/CPU/*.c))
KERNEL_ARCH_OBJS+=$(patsubst %.asm,%.o,$(wildcard $(ARCHDIR)/include/Device/CPU/*.asm))