CFLAGS+=-I $(Universal)
KERNEL_ARCH_OBJS+=\
$(Universal)/Die.o \
$(Universal)/Abstraction/DAL.o \
$(Universal)/Abstraction/VFS.o \
$(Universal)/StringConvert.o \
$(Universal)/KernelMain.o \
$(Universal)/PPI.o \
$(Universal)/PCI.o \
$(Universal)/Abstraction/Console.o