name: Build For Intel.PC/32

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v
    
    - name: All
      run: cd Source && make PROFILE=intel.pc.32.base.multiboot CC=i686-elf-gcc AS=nasm all
